version: "3.9"

services:
  navigation:
    container_name: navigation-app
    restart: always
    build:
      context: ./navigation-app/
      dockerfile: Dockerfile.dev
    ports:
      - "9000:3000"
    volumes:
      - ./navigation-app/:/nav-app
      - /nav-app/node_modules
  home:
    container_name: home-app
    build:
      context: ./home-app/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    restart: always
    volumes:
      - ./home-app/:/home-app
      - /home-app/node_modules
